# Generated by Django 4.0.5 on 2022-06-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220613_2355'),
    ]

    operations = [
    ]
