# Generated by Django 4.0.5 on 2022-06-14 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220614_2234'),
    ]

    operations = [
    ]
